2022-02-27T02:40:01.461562+00:00 app[web.1]: [2022-02-27 02:40:01 +0000] [9] [INFO] Booting worker with pid: 9
2022-02-27T02:40:01.464263+00:00 app[web.1]: [2022-02-27 02:40:01 +0000] [9] [ERROR] Exception in worker process
2022-02-27T02:40:01.464264+00:00 app[web.1]: Traceback (most recent call last):
2022-02-27T02:40:01.464281+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
2022-02-27T02:40:01.464281+00:00 app[web.1]: worker.init_process()
2022-02-27T02:40:01.464282+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
2022-02-27T02:40:01.464282+00:00 app[web.1]: self.load_wsgi()
2022-02-27T02:40:01.464282+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2022-02-27T02:40:01.464283+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2022-02-27T02:40:01.464286+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
2022-02-27T02:40:01.464286+00:00 app[web.1]: self.callable = self.load()
2022-02-27T02:40:01.464287+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2022-02-27T02:40:01.464287+00:00 app[web.1]: return self.load_wsgiapp()
2022-02-27T02:40:01.464287+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2022-02-27T02:40:01.464287+00:00 app[web.1]: return util.import_app(self.app_uri)
2022-02-27T02:40:01.464288+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
2022-02-27T02:40:01.464288+00:00 app[web.1]: mod = importlib.import_module(module)
2022-02-27T02:40:01.464288+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/importlib/__init__.py", line 127, in import_module
2022-02-27T02:40:01.464289+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2022-02-27T02:40:01.464289+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2022-02-27T02:40:01.464289+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2022-02-27T02:40:01.464290+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
2022-02-27T02:40:01.464290+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2022-02-27T02:40:01.464290+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2022-02-27T02:40:01.464291+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2022-02-27T02:40:01.464291+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
2022-02-27T02:40:01.464291+00:00 app[web.1]: ModuleNotFoundError: No module named 'djangoherokuapp'
2022-02-27T02:40:01.464339+00:00 app[web.1]: [2022-02-27 02:40:01 +0000] [9] [INFO] Worker exiting (pid: 9)
2022-02-27T02:40:01.464563+00:00 app[web.1]: [2022-02-27 02:40:01 +0000] [10] [INFO] Booting worker with pid: 10
2022-02-27T02:40:01.467412+00:00 app[web.1]: [2022-02-27 02:40:01 +0000] [10] [ERROR] Exception in worker process
2022-02-27T02:40:01.467413+00:00 app[web.1]: Traceback (most recent call last):
2022-02-27T02:40:01.467414+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
2022-02-27T02:40:01.467414+00:00 app[web.1]: worker.init_process()
2022-02-27T02:40:01.467415+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
2022-02-27T02:40:01.467415+00:00 app[web.1]: self.load_wsgi()
2022-02-27T02:40:01.467415+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2022-02-27T02:40:01.467416+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2022-02-27T02:40:01.467416+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
2022-02-27T02:40:01.467417+00:00 app[web.1]: self.callable = self.load()
2022-02-27T02:40:01.467417+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2022-02-27T02:40:01.467417+00:00 app[web.1]: return self.load_wsgiapp()
2022-02-27T02:40:01.467418+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2022-02-27T02:40:01.467418+00:00 app[web.1]: return util.import_app(self.app_uri)
2022-02-27T02:40:01.467418+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
2022-02-27T02:40:01.467419+00:00 app[web.1]: mod = importlib.import_module(module)
2022-02-27T02:40:01.467419+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/importlib/__init__.py", line 127, in import_module
2022-02-27T02:40:01.467419+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2022-02-27T02:40:01.467420+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2022-02-27T02:40:01.467420+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2022-02-27T02:40:01.467420+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
2022-02-27T02:40:01.467420+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2022-02-27T02:40:01.467421+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2022-02-27T02:40:01.467422+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2022-02-27T02:40:01.467422+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
2022-02-27T02:40:01.467423+00:00 app[web.1]: ModuleNotFoundError: No module named 'djangoherokuapp'
2022-02-27T02:40:01.467474+00:00 app[web.1]: [2022-02-27 02:40:01 +0000] [10] [INFO] Worker exiting (pid: 10)
2022-02-27T02:40:01.491582+00:00 app[web.1]: [2022-02-27 02:40:01 +0000] [4] [WARNING] Worker with pid 10 was terminated due to signal 15
2022-02-27T02:40:01.590668+00:00 app[web.1]: [2022-02-27 02:40:01 +0000] [4] [INFO] Shutting down: Master
2022-02-27T02:40:01.590697+00:00 app[web.1]: [2022-02-27 02:40:01 +0000] [4] [INFO] Reason: Worker failed to boot.
2022-02-27T02:40:01.761523+00:00 heroku[web.1]: Process exited with status 3
2022-02-27T02:40:01.834765+00:00 heroku[web.1]: State changed from starting to crashed
2022-02-27T02:40:01.850712+00:00 heroku[web.1]: State changed from crashed to starting
2022-02-27T02:40:04.000000+00:00 app[api]: Build succeeded
2022-02-27T02:40:06.662609+00:00 heroku[web.1]: Starting process with command `gunicorn djangoherokuapp.wsgi --log-file -`
2022-02-27T02:40:07.730343+00:00 app[web.1]: [2022-02-27 02:40:07 +0000] [4] [INFO] Starting gunicorn 20.1.0
2022-02-27T02:40:07.730713+00:00 app[web.1]: [2022-02-27 02:40:07 +0000] [4] [INFO] Listening at: http://0.0.0.0:45376 (4)
2022-02-27T02:40:07.730771+00:00 app[web.1]: [2022-02-27 02:40:07 +0000] [4] [INFO] Using worker: sync
2022-02-27T02:40:07.734229+00:00 app[web.1]: [2022-02-27 02:40:07 +0000] [9] [INFO] Booting worker with pid: 9
2022-02-27T02:40:07.736745+00:00 app[web.1]: [2022-02-27 02:40:07 +0000] [9] [ERROR] Exception in worker process
2022-02-27T02:40:07.736746+00:00 app[web.1]: Traceback (most recent call last):
2022-02-27T02:40:07.736761+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
2022-02-27T02:40:07.736761+00:00 app[web.1]: worker.init_process()
2022-02-27T02:40:07.736762+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
2022-02-27T02:40:07.736762+00:00 app[web.1]: self.load_wsgi()
2022-02-27T02:40:07.736762+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2022-02-27T02:40:07.736763+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2022-02-27T02:40:07.736763+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
2022-02-27T02:40:07.736764+00:00 app[web.1]: self.callable = self.load()
2022-02-27T02:40:07.736764+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2022-02-27T02:40:07.736764+00:00 app[web.1]: return self.load_wsgiapp()
2022-02-27T02:40:07.736764+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2022-02-27T02:40:07.736765+00:00 app[web.1]: return util.import_app(self.app_uri)
2022-02-27T02:40:07.736765+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
2022-02-27T02:40:07.736765+00:00 app[web.1]: mod = importlib.import_module(module)
2022-02-27T02:40:07.736765+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/importlib/__init__.py", line 127, in import_module
2022-02-27T02:40:07.736766+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2022-02-27T02:40:07.736766+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2022-02-27T02:40:07.736767+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2022-02-27T02:40:07.736767+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
2022-02-27T02:40:07.736767+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2022-02-27T02:40:07.736768+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2022-02-27T02:40:07.736768+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2022-02-27T02:40:07.736768+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
2022-02-27T02:40:07.736768+00:00 app[web.1]: ModuleNotFoundError: No module named 'djangoherokuapp'
2022-02-27T02:40:07.736816+00:00 app[web.1]: [2022-02-27 02:40:07 +0000] [9] [INFO] Worker exiting (pid: 9)
2022-02-27T02:40:07.759238+00:00 app[web.1]: [2022-02-27 02:40:07 +0000] [4] [INFO] Shutting down: Master
2022-02-27T02:40:07.759274+00:00 app[web.1]: [2022-02-27 02:40:07 +0000] [4] [INFO] Reason: Worker failed to boot.
2022-02-27T02:40:07.896911+00:00 heroku[web.1]: Process exited with status 3
2022-02-27T02:40:07.976506+00:00 heroku[web.1]: State changed from starting to crashed
2022-02-27T02:40:09.083706+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=ghost-reborn-website.herokuapp.com request_id=e38637d6-3940-4e95-aaf9-210b43b6cdce fwd="103.168.201.80" dyno= connect= service= status=503 bytes= protocol=https
